//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitkiler_hastaliklar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HASTALIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_HASTALIK()
        {
            this.TBLRecete = new HashSet<TBLRecete>();
        }
    
        public int hastalikID { get; set; }
        public string hastalikAdiTr { get; set; }
        public string hastalikAdiLatince { get; set; }
        public string hastalikGrubu { get; set; }
        public string hastalikTanim { get; set; }
        public string hastalikAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRecete> TBLRecete { get; set; }
    }
}
