//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitkiler_hastaliklar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_KULLANICI
    {
        public int kullaniciID { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciSoyadi { get; set; }
        public string kullaniciMail { get; set; }
        public string kullaniciSifre { get; set; }
        public Nullable<int> kullaniciYoneticiMi { get; set; }
    }
}
