//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitkiler_hastaliklar.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BITKI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_BITKI()
        {
            this.TBLRecete = new HashSet<TBLRecete>();
        }
    
        public int bitkiID { get; set; }
        public string bitkiAdiTr { get; set; }
        public string bitkiAdiLatince { get; set; }
        public string bitkiFoto { get; set; }
        public string bitkiAciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLRecete> TBLRecete { get; set; }
    }
}
